include dracula.conf
font_family      JetBrainsMono NFM
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 14.0

term xterm-256color
enable_audio_bell no

shell_integration no_cursor
cursor_blink_interval 0
open_url_with default
url_style curly
detect_urls yes
confirm_os_window_close 0
window_padding_width 10
disable_ligatures cursor

# if mac
macos_titlebar_color background
